  
jobs:
- job: PyUCISViewer_Linux
  pool:
   vmImage: 'ubuntu-18.04'

  variables:
  - name: build_num
    value: $(Build.BuildNumber)
  steps:
  - script: |
      python3 --version
      python3 -m pip install --upgrade pip 
      python3 -m pip install wheel twine 
      python3 -m pip install ivpm
      python3 -m pip install -r requirements_dev.txt 
    displayName: 'Install Python packages'
    
  - script: |
      python3 setup.py bdist_wheel --universal
    displayName: 'Build Wheel'

  - task: TwineAuthenticate@1
    condition: eq(variables['Build.SourceBranchName'], 'master')
    inputs:
      pythonUploadServiceConnection: pypi-pyucis-viewer
  - script: |
     # Only deploy from master
     if test "$(Build.SourceBranchName)" = "master"; then
         python3 -m twine --version
         echo "Calling twine"
         python3 -m twine upload -r pyucis-viewer --config-file $(PYPIRC_PATH) dist/*.whl
         echo "Calling twine complete"
     fi
    displayName: 'Upload to PyPi'


